version: "3.9"
services:
  backend:
    build: .
    container_name: akh-backend
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:7
    container_name: akh-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
