apiVersion: apps/v1
kind: Deployment
metadata:
  name: akh-frontend
  labels:
    app: akh-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: akh-frontend
  template:
    metadata:
      labels:
        app: akh-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/<YOUR_ORG>/ai-knowledge-hub-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: akh-frontend
spec:
  selector:
    app: akh-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
