apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akh-mongo
spec:
  selector:
    matchLabels:
      app: akh-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: akh-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: akh-mongo
spec:
  selector:
    app: akh-mongo
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  clusterIP: None
